# Generated by Django 4.2 on 2023-04-13 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorname', models.CharField(max_length=30)),
                ('authorid', models.IntegerField(max_length=9)),
            ],
            options={
                'db_table': 'authors',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('description', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bName', models.CharField(max_length=100)),
                ('bPrice', models.FloatField()),
                ('bQty', models.IntegerField()),
                ('bDesc', models.CharField(max_length=100, null=True)),
                ('bStatus', models.BooleanField(default=True)),
                ('bookAuthor', models.ForeignKey(max_length=30, null=True, on_delete=django.db.models.deletion.CASCADE, to='book.author')),
                ('bookCategory', models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='book.category')),
            ],
            options={
                'db_table': 'books',
            },
        ),
    ]
