# Generated by Django 4.2 on 2023-04-14 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='bDesc',
            new_name='bookDescription',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='bName',
            new_name='bookName',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='bPrice',
            new_name='bookPrice',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='bQty',
            new_name='bookQty',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='bStatus',
            new_name='bookStatus',
        ),
    ]
