# Generated by Django 4.2 on 2023-04-14 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_rename_bdesc_book_bookdescription_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='bookQty',
        ),
        migrations.AddField(
            model_name='book',
            name='bookQuantity',
            field=models.IntegerField(null=True),
        ),
    ]
