# Generated by Django 4.2 on 2023-04-14 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_book_bookimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='authorid',
        ),
    ]
